name: Generate TestRail Test Cases

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-test-cases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Verify script and environment
        run: |
          # Check if script exists and is readable
          if [ ! -f "scripts/generate_testrail_cases.py" ]; then
            echo "Error: scripts/generate_testrail_cases.py not found"
            exit 1
          fi
          
          # Make script executable
          chmod +x scripts/generate_testrail_cases.py
          
          # Verify Python can parse the script
          python -m py_compile scripts/generate_testrail_cases.py
          
          # Print Python version for debugging
          python --version
      
      - name: Generate and upload test cases
        # Pass secrets directly to the command instead of using environment variables
        run: |
          # Debug: Check if secrets are directly accessible
          echo "Checking if secrets are available through GitHub secrets context..."
          
          # Pass secrets directly from GitHub secrets context
          python scripts/generate_testrail_cases.py \
            --repo-path $GITHUB_WORKSPACE \
            --base-sha ${{ github.event.pull_request.base.sha }} \
            --head-sha ${{ github.event.pull_request.head.sha }} \
            --watsonx-api-key "${{ secrets.WATSONX_API_KEY }}" \
            --testrail-url "${{ secrets.TESTRAIL_URL }}" \
            --testrail-user "${{ secrets.TESTRAIL_USER }}" \
            --testrail-api-key "${{ secrets.TESTRAIL_API_KEY }}" \
            --project-id "${{ secrets.TESTRAIL_PROJECT_ID }}" \
            --suite-id "${{ secrets.TESTRAIL_SUITE_ID }}"

# Made with Bob
